version: "3"
volumes:
  kafka_21_data:
    driver: local
  zookeeper1_data:
    driver: local
  kafka_22_data:
    driver: local
networks:
  test-net:
    driver: overlay
    attachable: true
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper1_data:/bitnami/zookeeper
    networks:
      - test-net
    restart: always
  kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=21
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cb01.bu.ac.th:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://cb01.bu.ac.th:9092,EXTERNAL://cb01.bu.ac.th:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_21_data:/bitnami/kafka
    networks:
      - test-net
    restart: always
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
      - '9095:9095'
    environment:
      - KAFKA_BROKER_ID=22
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cb01.bu.ac.th:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://cb01.bu.ac.th:9094,EXTERNAL://cb01.bu.ac.th:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_22_data:/bitnami/kafka
    networks:
      - test-net
    restart: always
    depends_on:
      - zookeeper
