version: "3"
volumes:
  #zookeeper1_data:
  #  driver: local
  kafka_7_data:
    driver: local
  kafka_8_data:
    driver: local
  kafka_9_data:
    driver: local
networks:
  kafka-net:
    driver: overlay
    attachable: true
services:
  #zookeeper1:
    #image: 'bitnami/zookeeper:latest'
    #ports:cl
    #  - '2181:2181'
    #environment:
    #  - ALLOW_ANONYMOUS_LOGIN=yes
    #volumes:
    #  - zookeeper1_data:/bitnami/zookeeper
    #networks:
    #  - test-net
  kafka7:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
      - '9095:9095'
    environment:
      - KAFKA_BROKER_ID=7
      - KAFKA_CFG_ZOOKEEPER_CONNECT=bk01.bu.ac.th:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://bk03.bu.ac.th:9094,EXTERNAL://bk03.bu.ac.th:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_7_data:/bitnami/kafka
    networks:
      - kafka-net
    restart: always
    #depends_on:
    #  - zookeeper1
  kafka8:
    image: 'bitnami/kafka:latest'
    ports:
      - '9096:9096'
      - '9097:9097'
    environment:
      - KAFKA_BROKER_ID=8
      - KAFKA_CFG_ZOOKEEPER_CONNECT=bk01.bu.ac.th:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9096,EXTERNAL://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://bk03.bu.ac.th:9096,EXTERNAL://bk03.bu.ac.th:9097
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_8_data:/bitnami/kafka
    networks:
      - kafka-net
    restart: always
    #depends_on:
    #  - zookeeper1
  kafka9:
    image: 'bitnami/kafka:latest'
    ports:
      - '9098:9098'
      - '9099:9099'
    environment:
      - KAFKA_BROKER_ID=9
      - KAFKA_CFG_ZOOKEEPER_CONNECT=bk01.bu.ac.th:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9098,EXTERNAL://:9099
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://bk03.bu.ac.th:9098,EXTERNAL://cb03.bu.ac.th:9099
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_9_data:/bitnami/kafka
    networks:
      - kafka-net
    restart: always
    #depends_on:
    #  - zookeeper1